version: 2.1


orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
  aws-ecr: circleci/aws-ecr@6.11.0
  aws-ecs: circleci/aws-ecs@1.2.0
  slack: circleci/slack@3.4.2

commands:
  get-source-code:
    description: "Get source code from cache, if possible"
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

jobs:

  build:
    docker:
      - image: circleci/node:14.6.0-browsers
    # Switch from default medium machine (vCPUs: 2, RAM: 4GB) to large machine (vCPUs: 4, RAM: 8GB):
    # resource_class: large
    resource_class: small
    steps:
      - get-source-code
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:prod
            - persist_to_workspace:
                root: .
                paths:
                  - dist
      - store_artifacts:
          path: ./dist/browser
      - slack/notify-on-failure

  run-test:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    # Depending on the number of tests, we can increase number of parallel runs:
    parallelism: 2
    steps:
      - get-source-code
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
      - slack/notify-on-failure
      

  run-lint:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - get-source-code
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
      - slack/notify-on-failure

  run-sonarqube:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - get-source-code
      - node/with-cache:
          steps:
            - run: echo "Running Sonarqube [placeholder]"
            - run: sleep 30 # Fake SQ run. Hope it is enough for just a demo.
      - slack/notify-on-failure

  run-smoke-tests:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - run: echo "Running smoke tests [placeholder]"
      - slack/notify-on-failure

  run-uat:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - run: echo "Running User Acceptance Tests [placeholder]"
      - slack/notify-on-failure


  build-and-test-just-check:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - get-source-code
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run test
            - run: npm run build:prod
      - slack/notify-on-failure


  long-second-stage:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - run: echo "Test"


workflows:

  "Automated acceptance tests (long running)":
    triggers:
      - schedule:
          # To avoid eating all credits set current day number (1: Monday, 4: Thursday, etc.)
          # At minute 0 past hour 8, 10, 12, 14, 16, and 18 on Thursday.
          cron: "0 8,10,12,14,16,18 * * 4"
          filters:
            branches:
              only:
                - master
    jobs:
      - long-second-stage




    "Cobiro build check only":
      jobs:
        - build-and-test-just-check:
            name: "Build app. and run tests for side branches"
            filters:
              branches:
                ignore: master


    "Cobiro regular pipeline":
      jobs:
        - build:
            filters:
              branches:
                only: masterDELETE_ME

        - run-test:
            filters:
              branches:
                only: masterDELETE_ME

        - run-lint:
            filters:
              branches:
                only: masterDELETE_ME

        - run-sonarqube:
            filters:
              branches:
                only: masterDELETE_ME



        - aws-ecr/build-and-push-image:
            name: "Dockerize app. and push to repository"
            account-url: AWS_ECR_ACCOUNT_URL
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            create-repo: true
            attach-workspace: true
            dockerfile: Dockerfile
            no-output-timeout: 5m
            path: .
            region: AWS_REGION
            repo: angular9-example-app
            skip-when-tags-exist: false
            tag: "latest,${CIRCLE_SHA1}"
            requires:
              - build
              - run-test
              - run-lint
              - run-sonarqube
            filters:
              branches:
                only: master

        - aws-ecs/deploy-service-update:
            name: "Deploy to DEV"
            requires:
              - "Dockerize app. and push to repository"
            family: 'cobiro-dev-task-definition'
            cluster-name: 'cobiro-dev-cluster'
            service-name: 'cobiro-dev-service'
            container-image-name-updates: "container=cobiro-dev-container,tag=${CIRCLE_SHA1}"
            filters:
              branches:
                only: master

        - run-smoke-tests:
            name: "Smoke tests after deploying to DEV"
            requires:
              - "Deploy to DEV"
            filters:
              branches:
                only: master


        - deploy-to-qa-approval:
            name: "Approval before deployment to QA"
            type: approval
            requires:
              - "Smoke tests after deploying to DEV"
            filters:
              branches:
                only: master

        - aws-ecs/deploy-service-update:
            name: "Deploy to QA"
            requires:
              - "Approval before deployment to QA"
            family: 'cobiro-qa-task-definition'
            cluster-name: 'cobiro-qa-cluster'
            service-name: 'cobiro-qa-service'
            container-image-name-updates: "container=cobiro-qa-container,tag=${CIRCLE_SHA1}"
            filters:
              branches:
                only: master

        - run-uat:
            name: "User Acceptance Testing on QA"
            requires:
              - "Deploy to QA"
            filters:
              branches:
                only: master


        - deploy-to-prod-approval:
            name: "Approval before deployment to PROD"
            type: approval
            requires:
              - "User Acceptance Testing on QA"
            filters:
              branches:
                only: master

        - aws-ecs/deploy-service-update:
            name: "Deploy to PROD"
            requires:
              - "Approval before deployment to PROD"
            family: 'cobiro-prod-task-definition'
            cluster-name: 'cobiro-prod-cluster'
            service-name: 'cobiro-prod-service'
            container-image-name-updates: "container=cobiro-prod-container,tag=${CIRCLE_SHA1}"
            filters:
              branches:
                only: master
