version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
  aws-ecr: circleci/aws-ecr@6.11.0
  aws-ecs: circleci/aws-ecs@1.2.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - browser-tools/install-chrome
            #- run: npm install
            #- run: npm run lint
            #- run: npm run test
            #- run: npm run build:prod

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - aws-ecr/build-and-push-image:
            account-url: AWS_ECR_ACCOUNT_URL
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            create-repo: true
            dockerfile: Dockerfile
            no-output-timeout: 20m
            path: .
            region: AWS_REGION
            repo: angular9-example-app
            tag: 'latest,0.0.1'
            requires:
              - build-and-test
        - aws-ecs/deploy-service-update:
            requires:
              - aws-ecr/build-and-push-image
            family: "${AWS_RESOURCE_NAME_PREFIX}-service"
            cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
            container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=latest"
